force-app/main/default/objects/Hasta__c/Hasta__c.object-meta.xml
<CustomObject>
    <label>Hasta</label>
    <nameField>
        <label>Hasta Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hastalar</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hasta__c/fields/Doktor__c.field-meta.xml
<CustomField>
    <fullName>Doktor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Doktor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Hastalar</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hasta__c/fields/Hemsire__c.field-meta.xml
<CustomField>
    <fullName>Hemsire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hemsire</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Hastalar1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HastaTriggerHandler.cls
public class HastaTriggerHandler {
    public static void hastaPaylasimMethodu(list<Hasta__c>hastalist){
         /*  Hasta__Share yeniPaylasim = new Hasta__Share();
           yeniPaylasim.ParentId = hastaIdsi;  //   paylasilacak hasta id si
           yeniPaylasim.UserOrGroupId = paylasilacakKisiIdsi;  //  kiminle paylasilacak
           yeniPaylasim.AccessLevel = 'Edit';      // yetkisi ne olacak
           yeniPaylasim.RowCause = 'Manual';
        return yeniPaylasim;*/
        
        List<hasta__Share> hastaListesi = new List<hasta__Share>();
            for(Hasta__c hasta:hastalist){
             Hasta__Share yeniPaylasim = new Hasta__Share();
               yeniPaylasim.ParentId = hasta.id ;  //   paylasilacak hasta id si
               yeniPaylasim.UserOrGroupId = hasta.Hemsire__c;  //  kiminle paylasilacak
               yeniPaylasim.AccessLevel = 'Edit';      // yetkisi ne olacak
               yeniPaylasim.RowCause = 'Manual';
               hastaListesi.add(yeniPaylasim);
            }
            for(Hasta__c hasta:hastalist){
             Hasta__Share yeniPaylasim = new Hasta__Share();
               yeniPaylasim.ParentId = hasta.id ;  //   paylasilacak hasta id si
               yeniPaylasim.UserOrGroupId = hasta.Doktor__c;  //  kiminle paylasilacak
               yeniPaylasim.AccessLevel = 'Edit';      // yetkisi ne olacak
               yeniPaylasim.RowCause = 'Manual';
               hastaListesi.add(yeniPaylasim);
            }
         insert hastaListesi;
        
        
        
    }
}